/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {useState} from 'react';
import {StyleSheet, Text, View, Button, Linking, TextInput} from 'react-native';
import GetnetHardwareCommunication from 'react-native-getnet-hardware-communication';

export default function App() {
  const [status, setStatus] = useState('starting');
  const [message, setMessage] = useState('message');
  async function print() {
    const responsePrint = await GetnetHardwareCommunication.printMethod({
      // 1 - 5;
      setFontGray: 5,
      //choice a size
      fontSize: 'small',
      //using text(small<48 || medium && large << 36) and position
      //Bitmap width: 378 pixels
      textPrint: [
        {
          text: 'text write or path_bitmap',
          position: 'bitmap-1',
        },
        {
          text: 'text write or path_bitmap',
          position: 'left',
        },
        {
          text: 'text write or path_bitmap',
          position: 'center',
        },
        //Example BITMAP -> bitmap-0 (left), bitmap-1 (central), bitmap-2 (rigth);
        //Example Text
        {text: 'text implementation', position: 'center'},
        ,
      ],
    });
  }
  async function printView() {
    const data = await GetnetHardwareCommunication.printView({
      textPrint: [
        {
          text: 'Anderson',
          position: 'bitmap',
          fontSize: 'small',
          setFontGray: 5,
        },
        {
          text: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCE56789',
          position: 'center',
          setFontGray: 5,
          fontSize: 'small',
        },
        {
          text:
            'ABCDEFGHIJKLMNOPQRSTUVWXYZ012349ABCEGHIJKLMNOPQRSTUVWXYZ123456789',
          position: 'center',
          setFontGray: 5,
          fontSize: 'small',
        },
        {
          text: 'ABCDEFGHIJKLMNOPYZ123456789',
          position: 'center',
          setFontGray: 5,
          fontSize: 'small',
        },
        {
          text: 'ABCDEFGHIJKLMNOPQRSTUABCEGHIJKLMNOPQRSTUVWXYZ123456789',
          position: 'center',
          setFontGray: 5,
          fontSize: 'small',
        },
      ],
    });
    for (let i = 0; i < data.length; i++) {
      console.log(data[i]);
    }
  }
  return (
    <View style={styles.container}>
      <Text style={styles.welcome}>☆Geolocation example☆</Text>
      <Text style={styles.instructions}>STATUS: {status}</Text>
      <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
      <Text style={styles.instructions}>{message}</Text>
      <TextInput
        placeholder={'type it the value(only number):'}
        style={styles.input}
        keyboardType="numeric"
      />
      <Button title="Press" onPress={() => print()} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
